# version: "3.8"      
services: 
  backend:
    build:
      context: ./backend
    image: quickey-backend:latest
    env_file:
      - ./backend/.env
    volumes:
      - upload_data:/app/uploads
    expose:
      - "5000"
    networks:
      - global-web
    restart: unless-stopped
    # Add proper signal handling  
    stop_signal: SIGINT
    stop_grace_period: 10s
    init: true  # This helps with signal handling
    # user: "node:node" # run it as a non root user
    # command: node dist/index.js
   
    # This service runs the build and then exits    
  frontend-builder:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - /home/jotalac/quickey_app/frontend:/app
    command: sh -c "npm install && npm run build"

networks:
  global-web:
    external: true
    

volumes:
  caddy_data:
  caddy_config:
  upload_data: